### ISSUE TITLE
Datagrid row hover effect lags

### ISSUE THREAD

**Issue by marko-savic** [blazority/support#139] opened 2023-05-17 11:06 UTC
**Describe the bug**
On compact Datagrid, when the mouse hovers over the rows, the background color change lags. See the gif provided.
Not sure if it is a bug. However, I'm having trouble finding a root cause.

**To Reproduce**
Can not reproduce it locally, reproducible only after being deployed on a server.

**Environment**
 - Blazority Version 1.11
 - .NET Core Version 7
 - Browser Chrome, Edge

![row_hover_lag](https://github.com/blazority/support/assets/6500658/42ecce8b-6758-4b2a-b409-2705c8be59e6)

**Comment by karan-kang** [comment] 2023-05-22 16:06
@marko-savic Unfortunately, I am unable to reproduce this on my end (tried on both Wasm and Blazor hosted models).  Is you application doing anything else that is processor intensive? Where is it deployed? It feels like an issue with Blazor server rendering latency.

**Comment by marko-savic** [comment] 2023-05-23 04:16
@karan-kang the app is doing nothing except that. 
It should be reproducible only with Server side hosting model. 
I dig in a little bit and the root cause of the problem is definitely server latency. The Datgrid is changing the DOM by adding and removing CSS class "row-selected", which has the side effect of coloring the row same as :hover.  So, the row gets color from :hover and from adding class "row-hover" which stays longer due to lag.  You can see it in the gif below.

![rhl_css](https://github.com/blazority/support/assets/6500658/181faa7d-5ea3-4ddb-bd63-b1dff45e9987)

SingalR syncing  changes over WS:
![rhl_ws](https://github.com/blazority/support/assets/6500658/05d19bff-88b1-4d68-8357-44c1cb298284)

Ping to the server is ~280ms, which is bad regardless of this.

The only option I can see is to stop adding and removing "row-hover", but not sure what implication would that trigger.

All in all, it is the limitations of the current Server side hosting model, will try it in dotnet 8, and hope it can be overcome by pushing the component to be rendered by the client.

**Comment by karan-kang** [comment] 2023-10-14 21:34
Closing since the issue is not with Blazority but rather the application/server hosting.

**Closed by karan-kang** 2023-10-14 21:34 UTC
Labels: cannot reproduce
