### ISSUE TITLE
Datagrid:expandable row has an extra col

### ISSUE THREAD

**Issue by PamyAnnPatrick** [blazority/support#4] opened 2021-02-25 23:19 UTC
**Description**

Expandable rows has an extra col in the data grid when the table layout is fixed.

**Environment**

OS: Windows 10
Browse: Edge
Blazority Version: 0.6.2
.NET Core Version: 3.1

**Comment by karan-kang** [comment] 2021-03-15 03:28
Fixed in 0.6.2

**Comment by karan-kang** [comment] 2021-03-25 16:10
Reopening due to regression found in 0.6.3

**Closed** 2021-03-26 03:24 UTC
Labels: bug
