### ISSUE TITLE
Localized Message when Loading Data

### ISSUE THREAD

**Issue by pufpufpuf** [blazority/support#75] opened 2022-04-22 15:23 UTC
**Feature Type**
[ ] Clarity Port
[ x ] Enhancement

**Description**
When loading async paginated data the message goes : 'Please wait, retrieving items...'
Would be nice to have the possibility to edit this message to be able to have a localized message here for the user.

**Comment by karan-kang** [comment] 2022-04-25 00:55
Duplicate of #42, will be supported in v0.11.0

**Closed by karan-kang** 2022-04-25 00:55 UTC
Labels: bug, duplicate
