### ISSUE TITLE
Datagrid action popup didn´t disappear after clicking

### ISSUE THREAD

**Issue by thg87** [blazority/support#85] opened 2022-05-13 06:10 UTC
**Describe the bug**
Datagrid action popup didn´t disappear after clicking. The Action Popup is always visible after clicking on one item.

**Environment**
 - Blazority Version: 6.0.1
 - .NET Core Version: 6.0
 - Browser: Edge

**Comment by karan-kang** [comment] 2022-05-14 01:47
Closing as duplicate of #67

**Closed by karan-kang** 2022-05-14 01:47 UTC
Labels: duplicate
