### ISSUE TITLE
NavItem using one of the EventCallbacks breaks functionality.

### ISSUE THREAD

**Issue by PR33T0** [blazority/support#125] opened 2023-01-04 14:33 UTC
**Describe the bug**
If you overrride the onclick or the ActiveChanged event on a NavItem, You break the functionality that is default there.

if you add an onclick event this code is no longer executed:
`    protected override Task OnClickHandler(MouseEventArgs ev)
    {
      if (string.IsNullOrWhiteSpace(this.hrefAbsolute) && (this.ParentNav != null || this.ParentGroup != null))
        this.SetIsActive(true);
      return base.OnClickHandler(ev);
    }`

same for the ActiveChanged.

**Comment by karan-kang** [comment] 2023-01-15 21:17
@PR33T0 Can you show an example of what your override looks like?
Remember: If you doing an override, you need to call the base methods.

**Comment by PR33T0** [comment] 2023-01-16 06:29
![image](https://user-images.githubusercontent.com/6017565/212611957-fd7c7bbc-8746-4b25-8266-015cef0f4dd5.png)

    private async Task NavItemClicked()
    {
        var dimensions = await JsRuntime.InvokeAsync<WindowDimension>("getWindowDimensions");
        if (dimensions.Width < 576)
        {
           Toggleable = true;
        }
    }

I don't seem to be able to call the base method, but I just want my own code to be run next to the original code of the OnClick.
By attaching an OnClick I override the base function.

**Comment by karan-kang** [comment] 2023-01-16 13:25
@PR33T0 I see the issue now, I will have it fixed in upcoming release

**Comment by karan-kang** [comment] 2023-01-23 05:41
@PR33T0 I investigated this with the latest version and was unable to reproduce it.

You can see this behavior working in the Starter project for Blazority here:
https://github.com/blazority/Server.Starter/blob/master/Shared/NavMenu.razor

To test:
- Clone repo locally
- Add breakpoint in the FetchDataClicked method
- Launch app, navigate to "Fetch data" page
- FetchDataClicked method is invoked, and app successfully goes to "Fetch data" page as well

If you are still experiencing this, feel free to reopen

**Closed by karan-kang** 2023-01-23 05:41 UTC
Labels: cannot reproduce

**Comment by PR33T0** [comment] 2023-01-23 07:17
When navigating to the link I Get a 404. 
I will update to the latest version and retest.
